sudo: false
language: cpp
compiler: clang
matrix:
  include:
  - os: linux
    env: OS=ubuntu EASY_BUILD=x64
  - os: linux
    env: OS=ubuntu EASY_BUILD=arm
  - os: linux
    env: OS=ubuntu EASY_BUILD=hosted
  - os: linux
    env: OS=ubuntu EASY_BUILD=tests
  # - os: osx
  #   env: OS=osx EASY_BUILD=x64
  exclude:
    - os: linux
    - compiler: clang
script:
  - ./easy_build_$EASY_BUILD.sh nosudo $OS
  - if [[ "$EASY_BUILD" == "tests" ]]; then ./tests/testsuite.sh; fi
  - if [[ "$EASY_BUILD" != "tests" ]]; then ./scripts/runtest.py; fi
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qemu; fi
  - if [[ "$EASY_BUILD" == "tests" ]]; then pip install --user codecov gcovr; fi
after_success:
  - if [[ "$EASY_BUILD" == "tests" ]]; then codecov; fi
install: true
notifications:
  email: false
addons:
  apt:
    packages:
      - libmpfr-dev
      - libmpc-dev
      - libgmp3-dev
      - sqlite3
      - texinfo
      - scons
      - xorriso
      - e2fsprogs
      - qemu
      - nasm
      - uboot-mkimage
      - valgrind
cache:
  directories:
  - $HOME/.ccache
  - $HOME/pedigree-compiler
